apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pyspark-role-binding
  namespace: pyspark-depl
subjects:
  - kind: ServiceAccount
    name: pyspark-depl-service-account
    namespace: pyspark-depl
roleRef:
    kind: Role
    name: pyspark-role
    apiGroup: rbac.authorization.k8s.io