apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  namespace: pyspark-depl
  name: pyspark-role
rules: 
  - apiGroups: [""]
    resources: 
      - pods
      - pods/log
      - secrets
      - services
      - configmaps
    verbs:
      - get
      - list
      - create
      - delete
      - patch
      - watch
